# Generated by Django 4.0.5 on 2022-09-06 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inmobiliaria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_alta',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='fecha_publicacion',
        ),
    ]
