# Generated by Django 4.0.5 on 2022-10-03 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inmobiliaria', '0003_remove_propiedad_disponibilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='numeroprop',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
